print('   |\__/|   ')
print('   )    (   ')
print('  =\    /=  ')
print('    )==(    ')
print('   /    \   ')
print('  |      |  ')
print(' /        \ ')
print(' \        / ')
print('  \_    _/  ')
print('     ((     ')
print('      ))    ')
print('     ((     ')