print('  __________  ')
print(' |  ______  | ')
print(' | |      | | ')
print(' | |      | | ')
print(' | |      | | ')
print(' | |______| | ')
print(' |__________| ')
print('      ||      ')
print('      ||      ')
print('      ||      ')
print('     /  \     ')
print('    /    \    ')
print('   /      \   ')
print('  /________\  ')
